name: router.hk API client python package CI

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: Install the package
      run: |
        pip install .

    - name: Run tests
      run: |
          python -m unittest tests/test_routerhk.py
